// <auto-generated />
using System;
using Clinic.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Clinic.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251124183230_AddClinicSettingsTable")]
    partial class AddClinicSettingsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Clinic.Domain.Entities.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "92787aec-1266-4a2d-8a2d-6ea48f5a4811",
                            ConcurrencyStamp = "aee5e2f5-46b1-4ff7-8520-23fb69d75abd",
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "0d1fe96c-7786-4ce6-8647-38da6886a662",
                            ConcurrencyStamp = "1166ed41-1fa1-4d1f-9b6e-251a1706d31f",
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Doctor",
                            NormalizedName = "DOCTOR"
                        },
                        new
                        {
                            Id = "e6a5b8c2-6254-4279-866b-c916377576db",
                            ConcurrencyStamp = "0da76d1d-fcd3-41cd-bdf7-44f17e6e75e2",
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Secretary",
                            NormalizedName = "SECRETARY"
                        },
                        new
                        {
                            Id = "f4c051d8-f995-492c-8ef8-515417105616",
                            ConcurrencyStamp = "09e9d343-f279-48ad-98a1-96a37468d186",
                            IsDefault = true,
                            IsDeleted = false,
                            Name = "Patient",
                            NormalizedName = "PATIENT"
                        });
                });

            modelBuilder.Entity("Clinic.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.UseTptMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = "556c1c99-2d3a-4988-a80a-46ab2f14ea71",
                            AccessFailedCount = 0,
                            Address = "",
                            ConcurrencyStamp = "8680ddc2-d39a-41b4-9cb3-d0dc34d29708",
                            Email = "Admin@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Admin",
                            Gender = "",
                            IsDeleted = false,
                            IsDisabled = false,
                            IsOnline = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEMMgqpz9vGrgbTFmeBvuLwJ1xN0J0uwmJz/AOl1VoMJAQBJqWLH38d16IbCJcPrEoA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b2303bc6-6311-4036-851f-cae07c3b6d62",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        },
                        new
                        {
                            Id = "402ddff0-09e1-425f-b41b-2fc1ec5668b0",
                            AccessFailedCount = 0,
                            Address = "",
                            ConcurrencyStamp = "20d50f7d-c4cb-432c-8b33-00d0be480dae",
                            Email = "Secretary@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Secretary",
                            Gender = "",
                            IsDeleted = false,
                            IsDisabled = false,
                            IsOnline = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SECRETARY@GMAIL.COM",
                            NormalizedUserName = "SECRETARY",
                            PasswordHash = "AQAAAAIAAYagAAAAEDA3LGO1UCEdOI32j9Kn2f5qarw3RJfpgfBccRNKXKq5CkU4cNgYpOrIYig1oum+Rg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "07d283de-ef53-4afb-8c22-baf11dc263d5",
                            TwoFactorEnabled = false,
                            UserName = "Secretary"
                        });
                });

            modelBuilder.Entity("Clinic.Domain.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DoctorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReasonForVisit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimeSlotId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("VisitType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("TimeSlotId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Clinic.Domain.Entities.ClinicSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ClinicAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClinicName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClinicPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoctorDegree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoctorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoctorRegNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ClinicSettings");
                });

            modelBuilder.Entity("Clinic.Domain.Entities.ConnectionSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DisconnectedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ConnectionSessions");
                });

            modelBuilder.Entity("Clinic.Domain.Entities.DoctorSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DoctorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("DoctorSchedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Day = "Monday",
                            DoctorId = "57ff9f9a-6b56-4c6b-beeb-62cf2c6fd66e"
                        },
                        new
                        {
                            Id = 2,
                            Day = "Tuesday",
                            DoctorId = "57ff9f9a-6b56-4c6b-beeb-62cf2c6fd66e"
                        },
                        new
                        {
                            Id = 3,
                            Day = "Wednesday",
                            DoctorId = "57ff9f9a-6b56-4c6b-beeb-62cf2c6fd66e"
                        },
                        new
                        {
                            Id = 4,
                            Day = "Thursday",
                            DoctorId = "57ff9f9a-6b56-4c6b-beeb-62cf2c6fd66e"
                        },
                        new
                        {
                            Id = 5,
                            Day = "Friday",
                            DoctorId = "57ff9f9a-6b56-4c6b-beeb-62cf2c6fd66e"
                        },
                        new
                        {
                            Id = 6,
                            Day = "Saturday",
                            DoctorId = "57ff9f9a-6b56-4c6b-beeb-62cf2c6fd66e"
                        },
                        new
                        {
                            Id = 7,
                            Day = "Sunday",
                            DoctorId = "57ff9f9a-6b56-4c6b-beeb-62cf2c6fd66e"
                        });
                });

            modelBuilder.Entity("Clinic.Domain.Entities.DoctorTimeSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BookedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsBooked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.ToTable("TimeSlots");
                });

            modelBuilder.Entity("Clinic.Domain.Entities.MedicalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoctorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Treatment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("MedicalRecords");
                });

            modelBuilder.Entity("Clinic.Domain.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("ReceiverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Clinic.Domain.Entities.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("MedicalRecordId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("MedicalRecordId");

                    b.HasIndex("PatientId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("Clinic.Domain.Entities.PrescriptionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<string>("Instructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PrescriptionId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("PrescriptionId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("PrescriptionItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "permissions",
                            ClaimValue = "timeslots:read",
                            RoleId = "92787aec-1266-4a2d-8a2d-6ea48f5a4811"
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "permissions",
                            ClaimValue = "timeslots:add",
                            RoleId = "92787aec-1266-4a2d-8a2d-6ea48f5a4811"
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "permissions",
                            ClaimValue = "timeslots:update",
                            RoleId = "92787aec-1266-4a2d-8a2d-6ea48f5a4811"
                        },
                        new
                        {
                            Id = 4,
                            ClaimType = "permissions",
                            ClaimValue = "timeslots:delete",
                            RoleId = "92787aec-1266-4a2d-8a2d-6ea48f5a4811"
                        },
                        new
                        {
                            Id = 5,
                            ClaimType = "permissions",
                            ClaimValue = "medicalrecords:read",
                            RoleId = "92787aec-1266-4a2d-8a2d-6ea48f5a4811"
                        },
                        new
                        {
                            Id = 6,
                            ClaimType = "permissions",
                            ClaimValue = "medicalrecords:add",
                            RoleId = "92787aec-1266-4a2d-8a2d-6ea48f5a4811"
                        },
                        new
                        {
                            Id = 7,
                            ClaimType = "permissions",
                            ClaimValue = "medicalrecords:update",
                            RoleId = "92787aec-1266-4a2d-8a2d-6ea48f5a4811"
                        },
                        new
                        {
                            Id = 8,
                            ClaimType = "permissions",
                            ClaimValue = "medicalrecords:delete",
                            RoleId = "92787aec-1266-4a2d-8a2d-6ea48f5a4811"
                        },
                        new
                        {
                            Id = 9,
                            ClaimType = "permissions",
                            ClaimValue = "prescriptions:read",
                            RoleId = "92787aec-1266-4a2d-8a2d-6ea48f5a4811"
                        },
                        new
                        {
                            Id = 10,
                            ClaimType = "permissions",
                            ClaimValue = "prescriptions:add",
                            RoleId = "92787aec-1266-4a2d-8a2d-6ea48f5a4811"
                        },
                        new
                        {
                            Id = 11,
                            ClaimType = "permissions",
                            ClaimValue = "prescriptions:update",
                            RoleId = "92787aec-1266-4a2d-8a2d-6ea48f5a4811"
                        },
                        new
                        {
                            Id = 12,
                            ClaimType = "permissions",
                            ClaimValue = "prescriptions:delete",
                            RoleId = "92787aec-1266-4a2d-8a2d-6ea48f5a4811"
                        },
                        new
                        {
                            Id = 13,
                            ClaimType = "permissions",
                            ClaimValue = "appointments:read",
                            RoleId = "92787aec-1266-4a2d-8a2d-6ea48f5a4811"
                        },
                        new
                        {
                            Id = 14,
                            ClaimType = "permissions",
                            ClaimValue = "appointments:read-own",
                            RoleId = "92787aec-1266-4a2d-8a2d-6ea48f5a4811"
                        },
                        new
                        {
                            Id = 15,
                            ClaimType = "permissions",
                            ClaimValue = "appointments:add",
                            RoleId = "92787aec-1266-4a2d-8a2d-6ea48f5a4811"
                        },
                        new
                        {
                            Id = 16,
                            ClaimType = "permissions",
                            ClaimValue = "appointments:update",
                            RoleId = "92787aec-1266-4a2d-8a2d-6ea48f5a4811"
                        },
                        new
                        {
                            Id = 17,
                            ClaimType = "permissions",
                            ClaimValue = "appointments:cancel",
                            RoleId = "92787aec-1266-4a2d-8a2d-6ea48f5a4811"
                        },
                        new
                        {
                            Id = 18,
                            ClaimType = "permissions",
                            ClaimValue = "appointments:delete",
                            RoleId = "92787aec-1266-4a2d-8a2d-6ea48f5a4811"
                        },
                        new
                        {
                            Id = 19,
                            ClaimType = "permissions",
                            ClaimValue = "users:read",
                            RoleId = "92787aec-1266-4a2d-8a2d-6ea48f5a4811"
                        },
                        new
                        {
                            Id = 20,
                            ClaimType = "permissions",
                            ClaimValue = "users:add",
                            RoleId = "92787aec-1266-4a2d-8a2d-6ea48f5a4811"
                        },
                        new
                        {
                            Id = 21,
                            ClaimType = "permissions",
                            ClaimValue = "users:update",
                            RoleId = "92787aec-1266-4a2d-8a2d-6ea48f5a4811"
                        },
                        new
                        {
                            Id = 22,
                            ClaimType = "permissions",
                            ClaimValue = "roles:read",
                            RoleId = "92787aec-1266-4a2d-8a2d-6ea48f5a4811"
                        },
                        new
                        {
                            Id = 23,
                            ClaimType = "permissions",
                            ClaimValue = "roles:add",
                            RoleId = "92787aec-1266-4a2d-8a2d-6ea48f5a4811"
                        },
                        new
                        {
                            Id = 24,
                            ClaimType = "permissions",
                            ClaimValue = "roles:update",
                            RoleId = "92787aec-1266-4a2d-8a2d-6ea48f5a4811"
                        },
                        new
                        {
                            Id = 25,
                            ClaimType = "permissions",
                            ClaimValue = "results:read",
                            RoleId = "92787aec-1266-4a2d-8a2d-6ea48f5a4811"
                        },
                        new
                        {
                            Id = 26,
                            ClaimType = "permissions",
                            ClaimValue = "medicalrecords:read",
                            RoleId = "0d1fe96c-7786-4ce6-8647-38da6886a662"
                        },
                        new
                        {
                            Id = 27,
                            ClaimType = "permissions",
                            ClaimValue = "medicalrecords:add",
                            RoleId = "0d1fe96c-7786-4ce6-8647-38da6886a662"
                        },
                        new
                        {
                            Id = 28,
                            ClaimType = "permissions",
                            ClaimValue = "medicalrecords:update",
                            RoleId = "0d1fe96c-7786-4ce6-8647-38da6886a662"
                        },
                        new
                        {
                            Id = 29,
                            ClaimType = "permissions",
                            ClaimValue = "prescriptions:read",
                            RoleId = "0d1fe96c-7786-4ce6-8647-38da6886a662"
                        },
                        new
                        {
                            Id = 30,
                            ClaimType = "permissions",
                            ClaimValue = "prescriptions:add",
                            RoleId = "0d1fe96c-7786-4ce6-8647-38da6886a662"
                        },
                        new
                        {
                            Id = 31,
                            ClaimType = "permissions",
                            ClaimValue = "prescriptions:update",
                            RoleId = "0d1fe96c-7786-4ce6-8647-38da6886a662"
                        },
                        new
                        {
                            Id = 32,
                            ClaimType = "permissions",
                            ClaimValue = "prescriptions:delete",
                            RoleId = "0d1fe96c-7786-4ce6-8647-38da6886a662"
                        },
                        new
                        {
                            Id = 33,
                            ClaimType = "permissions",
                            ClaimValue = "appointments:read",
                            RoleId = "0d1fe96c-7786-4ce6-8647-38da6886a662"
                        },
                        new
                        {
                            Id = 34,
                            ClaimType = "permissions",
                            ClaimValue = "appointments:read",
                            RoleId = "e6a5b8c2-6254-4279-866b-c916377576db"
                        },
                        new
                        {
                            Id = 35,
                            ClaimType = "permissions",
                            ClaimValue = "appointments:add",
                            RoleId = "e6a5b8c2-6254-4279-866b-c916377576db"
                        },
                        new
                        {
                            Id = 36,
                            ClaimType = "permissions",
                            ClaimValue = "appointments:cancel",
                            RoleId = "e6a5b8c2-6254-4279-866b-c916377576db"
                        },
                        new
                        {
                            Id = 37,
                            ClaimType = "permissions",
                            ClaimValue = "timeslots:read",
                            RoleId = "e6a5b8c2-6254-4279-866b-c916377576db"
                        },
                        new
                        {
                            Id = 38,
                            ClaimType = "permissions",
                            ClaimValue = "users:read",
                            RoleId = "e6a5b8c2-6254-4279-866b-c916377576db"
                        },
                        new
                        {
                            Id = 39,
                            ClaimType = "permissions",
                            ClaimValue = "appointments:add",
                            RoleId = "f4c051d8-f995-492c-8ef8-515417105616"
                        },
                        new
                        {
                            Id = 40,
                            ClaimType = "permissions",
                            ClaimValue = "appointments:read-own",
                            RoleId = "f4c051d8-f995-492c-8ef8-515417105616"
                        },
                        new
                        {
                            Id = 41,
                            ClaimType = "permissions",
                            ClaimValue = "appointments:cancel",
                            RoleId = "f4c051d8-f995-492c-8ef8-515417105616"
                        },
                        new
                        {
                            Id = 42,
                            ClaimType = "permissions",
                            ClaimValue = "timeslots:read",
                            RoleId = "f4c051d8-f995-492c-8ef8-515417105616"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "556c1c99-2d3a-4988-a80a-46ab2f14ea71",
                            RoleId = "92787aec-1266-4a2d-8a2d-6ea48f5a4811"
                        },
                        new
                        {
                            UserId = "57ff9f9a-6b56-4c6b-beeb-62cf2c6fd66e",
                            RoleId = "0d1fe96c-7786-4ce6-8647-38da6886a662"
                        },
                        new
                        {
                            UserId = "402ddff0-09e1-425f-b41b-2fc1ec5668b0",
                            RoleId = "e6a5b8c2-6254-4279-866b-c916377576db"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Clinic.Domain.Entities.Doctor", b =>
                {
                    b.HasBaseType("Clinic.Domain.Entities.ApplicationUser");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("YearOfExperience")
                        .HasColumnType("int");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = "57ff9f9a-6b56-4c6b-beeb-62cf2c6fd66e",
                            AccessFailedCount = 0,
                            Address = "",
                            ConcurrencyStamp = "fa771ca3-a9cc-492f-8109-8bec8c38913b",
                            Email = "Doctor@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Doctor",
                            Gender = "",
                            IsDeleted = false,
                            IsDisabled = false,
                            IsOnline = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR@GMAIL.COM",
                            NormalizedUserName = "DOCTOR",
                            PasswordHash = "AQAAAAIAAYagAAAAEIG5s81etlP4CKbWdbtOT/Yil3RkMZ02qqgzWhpQi5hribuyH/eTiya1j91Wy7jbWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "33666ec9-580c-4814-90e6-7797aa01cf23",
                            TwoFactorEnabled = false,
                            UserName = "Doctor",
                            Specialization = "Cardiology",
                            YearOfExperience = 10
                        });
                });

            modelBuilder.Entity("Clinic.Domain.Entities.Patient", b =>
                {
                    b.HasBaseType("Clinic.Domain.Entities.ApplicationUser");

                    b.Property<DateOnly?>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("date");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Clinic.Domain.Entities.ApplicationUser", b =>
                {
                    b.OwnsMany("Clinic.Domain.Entities.RefreshToken", "RefreshTokens", b1 =>
                        {
                            b1.Property<string>("UserId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<DateTime>("CreatedOn")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("ExpiresOn")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("RevokedOn")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Token")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UserId", "Id");

                            b1.ToTable("RefreshTokens", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Clinic.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("Clinic.Domain.Entities.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("Clinic.Domain.Entities.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clinic.Domain.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clinic.Domain.Entities.DoctorTimeSlot", "TimeSlot")
                        .WithMany()
                        .HasForeignKey("TimeSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clinic.Domain.Entities.ApplicationUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.Navigation("CreatedBy");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("TimeSlot");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Clinic.Domain.Entities.ClinicSettings", b =>
                {
                    b.OwnsOne("Clinic.Domain.Entities.WorkHours", "WorkHours", b1 =>
                        {
                            b1.Property<int>("ClinicSettingsId")
                                .HasColumnType("int");

                            b1.HasKey("ClinicSettingsId");

                            b1.ToTable("ClinicSettings");

                            b1.WithOwner()
                                .HasForeignKey("ClinicSettingsId");

                            b1.OwnsOne("Clinic.Domain.Entities.DayHours", "Friday", b2 =>
                                {
                                    b2.Property<int>("WorkHoursClinicSettingsId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Close")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<bool?>("IsClose")
                                        .HasColumnType("bit");

                                    b2.Property<string>("Open")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("WorkHoursClinicSettingsId");

                                    b2.ToTable("ClinicSettings");

                                    b2.WithOwner()
                                        .HasForeignKey("WorkHoursClinicSettingsId");
                                });

                            b1.OwnsOne("Clinic.Domain.Entities.DayHours", "Monday", b2 =>
                                {
                                    b2.Property<int>("WorkHoursClinicSettingsId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Close")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<bool?>("IsClose")
                                        .HasColumnType("bit");

                                    b2.Property<string>("Open")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("WorkHoursClinicSettingsId");

                                    b2.ToTable("ClinicSettings");

                                    b2.WithOwner()
                                        .HasForeignKey("WorkHoursClinicSettingsId");
                                });

                            b1.OwnsOne("Clinic.Domain.Entities.DayHours", "Saturday", b2 =>
                                {
                                    b2.Property<int>("WorkHoursClinicSettingsId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Close")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<bool?>("IsClose")
                                        .HasColumnType("bit");

                                    b2.Property<string>("Open")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("WorkHoursClinicSettingsId");

                                    b2.ToTable("ClinicSettings");

                                    b2.WithOwner()
                                        .HasForeignKey("WorkHoursClinicSettingsId");
                                });

                            b1.OwnsOne("Clinic.Domain.Entities.DayHours", "Sunday", b2 =>
                                {
                                    b2.Property<int>("WorkHoursClinicSettingsId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Close")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<bool?>("IsClose")
                                        .HasColumnType("bit");

                                    b2.Property<string>("Open")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("WorkHoursClinicSettingsId");

                                    b2.ToTable("ClinicSettings");

                                    b2.WithOwner()
                                        .HasForeignKey("WorkHoursClinicSettingsId");
                                });

                            b1.OwnsOne("Clinic.Domain.Entities.DayHours", "Thursday", b2 =>
                                {
                                    b2.Property<int>("WorkHoursClinicSettingsId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Close")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<bool?>("IsClose")
                                        .HasColumnType("bit");

                                    b2.Property<string>("Open")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("WorkHoursClinicSettingsId");

                                    b2.ToTable("ClinicSettings");

                                    b2.WithOwner()
                                        .HasForeignKey("WorkHoursClinicSettingsId");
                                });

                            b1.OwnsOne("Clinic.Domain.Entities.DayHours", "Tuesday", b2 =>
                                {
                                    b2.Property<int>("WorkHoursClinicSettingsId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Close")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<bool?>("IsClose")
                                        .HasColumnType("bit");

                                    b2.Property<string>("Open")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("WorkHoursClinicSettingsId");

                                    b2.ToTable("ClinicSettings");

                                    b2.WithOwner()
                                        .HasForeignKey("WorkHoursClinicSettingsId");
                                });

                            b1.OwnsOne("Clinic.Domain.Entities.DayHours", "Wednesday", b2 =>
                                {
                                    b2.Property<int>("WorkHoursClinicSettingsId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Close")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<bool?>("IsClose")
                                        .HasColumnType("bit");

                                    b2.Property<string>("Open")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("WorkHoursClinicSettingsId");

                                    b2.ToTable("ClinicSettings");

                                    b2.WithOwner()
                                        .HasForeignKey("WorkHoursClinicSettingsId");
                                });

                            b1.Navigation("Friday");

                            b1.Navigation("Monday");

                            b1.Navigation("Saturday");

                            b1.Navigation("Sunday");

                            b1.Navigation("Thursday");

                            b1.Navigation("Tuesday");

                            b1.Navigation("Wednesday");
                        });

                    b.Navigation("WorkHours")
                        .IsRequired();
                });

            modelBuilder.Entity("Clinic.Domain.Entities.DoctorSchedule", b =>
                {
                    b.HasOne("Clinic.Domain.Entities.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Clinic.Domain.Entities.DoctorTimeSlot", b =>
                {
                    b.HasOne("Clinic.Domain.Entities.DoctorSchedule", "Schedule")
                        .WithMany("TimeSlots")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Clinic.Domain.Entities.MedicalRecord", b =>
                {
                    b.HasOne("Clinic.Domain.Entities.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("Clinic.Domain.Entities.Doctor", "Doctor")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clinic.Domain.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clinic.Domain.Entities.ApplicationUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.Navigation("CreatedBy");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Clinic.Domain.Entities.Message", b =>
                {
                    b.HasOne("Clinic.Domain.Entities.ApplicationUser", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clinic.Domain.Entities.ApplicationUser", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Clinic.Domain.Entities.Prescription", b =>
                {
                    b.HasOne("Clinic.Domain.Entities.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("Clinic.Domain.Entities.MedicalRecord", "MedicalRecord")
                        .WithMany()
                        .HasForeignKey("MedicalRecordId");

                    b.HasOne("Clinic.Domain.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clinic.Domain.Entities.ApplicationUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.Navigation("CreatedBy");

                    b.Navigation("MedicalRecord");

                    b.Navigation("Patient");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Clinic.Domain.Entities.PrescriptionItem", b =>
                {
                    b.HasOne("Clinic.Domain.Entities.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("Clinic.Domain.Entities.Prescription", "Prescription")
                        .WithMany("Items")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clinic.Domain.Entities.ApplicationUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.Navigation("CreatedBy");

                    b.Navigation("Prescription");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Clinic.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Clinic.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Clinic.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Clinic.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clinic.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Clinic.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Clinic.Domain.Entities.Doctor", b =>
                {
                    b.HasOne("Clinic.Domain.Entities.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Clinic.Domain.Entities.Doctor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Clinic.Domain.Entities.Patient", b =>
                {
                    b.HasOne("Clinic.Domain.Entities.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Clinic.Domain.Entities.Patient", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Clinic.Domain.Entities.DoctorSchedule", b =>
                {
                    b.Navigation("TimeSlots");
                });

            modelBuilder.Entity("Clinic.Domain.Entities.Prescription", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Clinic.Domain.Entities.Doctor", b =>
                {
                    b.Navigation("MedicalRecords");
                });

            modelBuilder.Entity("Clinic.Domain.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
